# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus_content',
            name='good',
        ),
        migrations.AddField(
            model_name='bonus_content',
            name='good',
            field=models.ManyToManyField(to='bonus.Good'),
        ),
    ]
