# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_auto_20160323_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus_content',
            name='good',
        ),
        migrations.AddField(
            model_name='bonus_content',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bonus.Good'),
            preserve_default=False,
        ),
    ]
