# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20160323_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_content',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.Good'),
        ),
    ]
