# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_auto_20160323_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_bonus',
            name='user',
            field=models.ForeignKey(default=b'a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
