# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_auto_20160323_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendNum', models.IntegerField()),
                ('recvNum', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsNum', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('consumerCount', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('whoPay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('openId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.BooleanField(default=True)),
                ('phoneNum', models.CharField(max_length=20)),
                ('idVIP', models.CharField(max_length=20)),
                ('isConsume', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumeInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.ConsumeInfo')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('indexTable', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('seats', models.IntegerField()),
                ('isPrivate', models.BooleanField()),
                ('isSync', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RcvBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.CharField(max_length=30)),
                ('rcvTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('fromMessage', models.CharField(max_length=45)),
                ('toMessage', models.CharField(max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Account')),
                ('consume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.ConsumeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RcvBonusContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SndBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.CharField(max_length=30)),
                ('createTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('toMessage', models.CharField(max_length=45)),
                ('fromMessage', models.CharField(max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SndBonusContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='deductible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bonus_content',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sndbonuscontent',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.Good'),
        ),
        migrations.AddField(
            model_name='sndbonuscontent',
            name='sndPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.SndBonus'),
        ),
        migrations.AddField(
            model_name='rcvbonuscontent',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.Good'),
        ),
        migrations.AddField(
            model_name='rcvbonuscontent',
            name='rcvPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.RcvBonus'),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='diningTable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.DiningTable'),
        ),
        migrations.AddField(
            model_name='accountcontent',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Good'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus.Consumer'),
        ),
    ]
