# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendBonusSum', models.IntegerField()),
                ('recvBonusSum', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsNum', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('user', models.ForeignKey(default=b'a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('left_quantity', models.IntegerField(default=0)),
                ('admin_bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Admin_bonus')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('consumerCount', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('whoPay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('openId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.BooleanField(default=True)),
                ('phoneNum', models.CharField(max_length=20)),
                ('idVIP', models.CharField(max_length=20)),
                ('isConsume', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumeInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.ConsumeInfo')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('indexTable', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('seats', models.IntegerField()),
                ('isPrivate', models.BooleanField()),
                ('isSync', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('deductible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RcvBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.CharField(max_length=30)),
                ('rcvTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('fromMessage', models.CharField(max_length=45)),
                ('toMessage', models.CharField(max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Account')),
                ('consume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.ConsumeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RcvBonusContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNum', models.IntegerField()),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixin.Good')),
                ('rcvPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.RcvBonus')),
            ],
        ),
        migrations.CreateModel(
            name='SndBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.CharField(max_length=30)),
                ('createTime', models.DateTimeField()),
                ('validTime', models.DateTimeField()),
                ('toMessage', models.CharField(max_length=45)),
                ('fromMessage', models.CharField(max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SndBonusContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNum', models.IntegerField()),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixin.Good')),
                ('sndPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.SndBonus')),
            ],
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='diningTable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixin.DiningTable'),
        ),
        migrations.AddField(
            model_name='bonus_content',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Good'),
        ),
        migrations.AddField(
            model_name='accountcontent',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Good'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
    ]
