# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='isConsume',
        ),
        migrations.AddField(
            model_name='consumer',
            name='isdining',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='recvBonusSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='sendBonusSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='totalPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
