# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20160328_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeinfo',
            name='consumerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumeinfo',
            name='totalPrice',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='isSync',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
